### ISSUE TITLE
Question- How is near-real time streaming achieved?

### ISSUE THREAD

**Issue by poornimajd** [hofbi/telecarla#19]
Hello,
Thank you for the great work!
I wanted to clarify the following points-
1.In the paper it is mentioned that by using a data-compressed streaming pipeline for video,you are able to transmit the video at 20fps.Does this apply to single camera or is it that all 6 cameras are able to transmit simultaneously at 20 fps?

2.Since ROS cannot transmit data over different networks,is this also one of the reasons for choosing gstreamer so that you can connect the remote driver to a network A and vehicle to network B?

Let me know your thoughts on this.
Thanks in advance.

**Comment by poornimajd** [comment]
Thanks for the prompt reply.Yes we might have to use ROS2 with telecarla in the near future.

>     2\. So if you are interested in using telecarla with ROS2 you would need to adapt the code by yourself, but use the carla ros bridge as template on how to support both version. If you plan to do this, I would be glad to answer further questions you might have.

Got it.
Thank you

**Comment by hofbi** [comment]
Just let me know when there are some unclear point. And feel free to provide your ROS2 changes as PR.
