### ISSUE TITLE
Question: Telecarla works with the latest Carla patch 0.9.12

### ISSUE THREAD

**Issue by pantelmen** [hofbi/telecarla#20]
Hello ,can telecarla works with the carla 0.9.12?

**Comment by hofbi** [comment]
In the current version 0.9.10.1 is supported. So far I did not publish/tag versions for 0.9.11 or 0.9.12 as the [carla ros bridge](https://github.com/carla-simulator/ros-bridge) does not provide those tags.

I already opened a PR in the ros bridge to support 0.9.12 at https://github.com/carla-simulator/ros-bridge/pull/563 and wait for this to be merged. 

But I will provide some changes to support 0.9.12. The changes mainly cover an updates in the sensor json structure for the ros bridge.

**Comment by pantelmen** [comment]
Firstly ty for replying too soon.Secondly i make my study for university.We
want to make a carla environment as a server and programming a car to run
inside the carla world,then we want to give the opportunity to an another
client to enter in our world and control a car or pedestrian remote from
his computer via the internet and interact with our car....i read your
paper and i think telecarla is that we are looking for....do you believe
that telecarla is what we need?
Ty in advance!

Στις Τετ, 18 Αυγ 2021, 6:05 μ.μ. ο χρήστης Markus Hofbauer <
***@***.***> έγραψε:

**Comment by hofbi** [comment]
Yes, this is the basic usecase telecarla is designed for.

With #21 I provide support for 0.9.12. I will try to merge it today once all checks pass.

**Comment by pantelmen** [comment]
thank you a lot

**Comment by hofbi** [comment]
The latest version now works with carla 0.9.12. But you need to use the carla-ros-bridge with the changes from https://github.com/carla-simulator/ros-bridge/pull/563
