### ISSUE TITLE
no camera image teleop gui from the client side

### ISSUE THREAD

**Issue by pantelmen** [hofbi/telecarla#23]
Helloo,
i run "roslaunch telecarla telecarla_single_local.launch" and the teleop gui open normally.Nevertheless,when i run "roslaunch telecarla telecarla_single_client.launch host:=<server_ip>" teleop gui opens without camera image,only a black window.I check the rostopic list and client topics exist.I see the sensors config and its ok after your update but the client teleop gui dont work correctly.Ty

**Comment by hofbi** [comment]
Do you have the telecarla_single_server.launch running somewhere as well? This is required as the server provides the video data as an RTSP stream and the client needs to connect to this. The client advertizes the topic right from the beginning, but as long as the client does not get any data from the server there won't be anything to show.

**Comment by pantelmen** [comment]
Yes i have the telecarla_sigle_server.launch running,but i running this in another pc without lan connection.We want to communicate via internet.Is it possible with telecarla? Maybe  should we use websocket or port forwarding for the communication?

**Comment by hofbi** [comment]
The connection type is not that important as the network. If you have both PCs in the same network (e.g. you can ssh/ping the server PC from the client), then the streaming should work.

If they are in two different networks, you could either use a VPN to bring them into the same network (might be an issue if you have a high transmission rate), or you need to make the server reachable through the internet. This is then something you need to do in you network configuration.

**Comment by hofbi** [comment]
Closing this since there is not update for a long time. Feel free to reopen in case the problem still exists.
