### ISSUE TITLE
Failed "catkin build"

### ISSUE THREAD

**Issue by VinalAsodia** [hofbi/telecarla#27]
I am trying to install TELECARLA and I am running into these errors when running the "catkin build" command. It is unable to complete the build jobs for telecarla_gui and gstreaming. I am on Linux 20.04 and am using ROS Noetic.

I have attached the relative log files and appreciate any help with the issue
[build.make.000.log](https://github.com/hofbi/telecarla/files/7883631/build.make.000.log)
[build.make.000.log](https://github.com/hofbi/telecarla/files/7883633/build.make.000.log)
!

**Comment by hofbi** [comment]
Based on you logs I guess you are missing the libhdf5 library. I am not sure why some packages depend on it. After a short websearch I found that you could try `apt install libhdf5-serial-dev`

**Comment by VinalAsodia** [comment]
I have executed the line of code you recommended and attached the console response. From the attached image it appears that I have the latest version of the package. Maybe the problem lies with incompatible package versions?
<img width="613" alt="telecarla issue" src="https://user-images.githubusercontent.com/47476885/149999417-a8d82eda-fa8a-4327-8853-b306e4d4dfc6.PNG">

**Comment by VinalAsodia** [comment]
> I have executed the line of code you recommended and attached the console response. From the attached image it appears that I have the latest version of the package. Maybe the problem lies with incompatible package versions? <img alt="telecarla issue" width="613" src="https://user-images.githubusercontent.com/47476885/149999417-a8d82eda-fa8a-4327-8853-b306e4d4dfc6.PNG">

I forgot to mention, when running the catkin build command again, I get the same log error message as given at the start of the thread.

**Comment by hofbi** [comment]
Since the CI passes, which is also based on an Ubunut 20.04, I assume that there is some local dependency missing on your system. Could you try to run the `install.sh` again, run a `catkin clean`, and then try again to build.

**Comment by VinalAsodia** [comment]
I have tried running the above commands again and attached the log information when running the install.sh script in case that is the source of error, as well as the console output at the beginning of the catkin build. 
[install_log.txt](https://github.com/hofbi/telecarla/files/7893201/install_log.txt)
<img width="387" alt="telecarla issue2" src="https://user-images.githubusercontent.com/47476885/150040440-943dba83-2d37-4561-a56c-84b1817daa57.PNG">

**Comment by hofbi** [comment]
Ok, the installation passes and everything required seems to be installed. When updating your packages right at the beginning of the script, you get some errors and warnings about apt sources, but I guess this should not be the problem.

Do you have access to another device, where you could try to setup telecarla?

Alternatively, you could try the docker image shiped with the repo. Using the compose file that is in the root dir, you can `docker compose build` and then `docker compose run telecarla`. You can run the CARLA server locally on your system and the telecerla container will connect to it.
