### ISSUE TITLE
[info] Incorporating Artifical Delay

### ISSUE THREAD

**Issue by amirx96** [hofbi/telecarla#4]
Hi,

Thank you for a great repo! Sorry to make an issue, but I was wondering how I could go about incorporating artificial video / input delay on a local teleop simulation. 

Would the best place be around [here](https://github.com/hofbi/telecarla/blob/26ae2d8786aa71dc8a8ca1421c933e71cdf23535/telecarla_gui/source/src/telecarla_gui.cpp#L88)?

Thank you!

**Comment by hofbi** [comment]
This would delay the event parser, which means the control command reading would be delayed. If you want to delay the image representation i guess the [ImageCallback](https://github.com/hofbi/telecarla/blob/26ae2d8786aa71dc8a8ca1421c933e71cdf23535/telecarla_gui/source/src/image_callback.cpp#L12) is a good place.

Another way of handling the delay is using the [tcgui](https://github.com/tum-lkn/tcgui) as mentioned in the paper. However setting the delay on localhost results in a delayed transmission of everything, so here I would suggest to run server and client in 2 docker containers. Then you should be able to perfectly control the delay and even more.

**Comment by amirx96** [comment]
Thank you. I did not think of using two Docker containers, that should work fine!
