### ISSUE TITLE
Sync CARLA with wall-time

### ISSUE THREAD

**Issue by 4336** [hofbi/telecarla#47]
I'm glad to find the study about remote driving.

I am also conducting a remote driving experiment in an environment using CARLA.

Meanwhile, I found that the CARLA uses its own time frame, and proceeds separately from the wall clock.

By default, the 'rostopic hz' command refers to the /clock topic by the use_sim_time parameter, so ROS users can easily miss understanding the time.

As a result of comparing the real-world time(use rostopic hz --wall-time), the simulation was faster or slower(depending on computational speed). (run about 40fps on 30fps setup)

It's not a big deal for the general CARLA community because they are not a human-in-the-loop system, but problems can occur with remote driving.

Is there any setting for these things in TELECARLA?

**Comment by hofbi** [comment]
Thank you for raising this issue. No, there is no setting in TELECARLA. TELECARLA is only taking care about the streaming part, so whatever frame rate you provide as input will be transmitted to the client. Everything related to the time has to be configured in CARLA.

**Comment by hofbi** [comment]
Thank you for raising this issue. No, there is no setting in TELECARLA. TELECARLA is only taking care about the streaming part, so whatever frame rate you provide as input will be transmitted to the client. Everything related to the time has to be configured in CARLA.

**Comment by 4336** [comment]
Thanks for the reply.

I solved the problem with the following setup.
=====
<arg name='synchronous_mode' default='True'/>
<arg name='synchronous_mode_wait_for_vehicle_control_command' default='True'/>
<arg name='fixed_delta_seconds' default='0.03333'/>
=====
And I created a new node that publishes the '/carla/ego_vehicle/vehicle_control_cmd_manual' topic at 30fps.
(using ros::WallRate and ros::spinOnce)

CARLA waits for a new control_cmd before all updates, so the speed should be limited to 30fps.

It seems like a quite crude solution, but it seems like it works for me, so I'll close the issue.

Thanks!
