### ISSUE TITLE
Resource not found: carla_ros_bridge

### ISSUE THREAD

**Issue by j4l-Shvn** [hofbi/telecarla#6]
Hi,

I am kind of a newbie on ROS while running locally (roslaunch telecarla telecarla_single_local.launch) I get the following..

Resource not found: carla_ros_bridge
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/subhojeet/Scratch/catkin_ws_teleop/src/telecarla/gstreaming
ROS path [2]=/home/subhojeet/Scratch/catkin_ws_teleop/src/telecarla/telecarla
ROS path [3]=/home/subhojeet/Scratch/catkin_ws_teleop/src/telecarla/telecarla_manual_control
ROS path [4]=/home/subhojeet/Scratch/catkin_ws_teleop/src/telecarla/telecarla_msgs
ROS path [5]=/home/subhojeet/Scratch/catkin_ws_teleop/src/telecarla/telecarla_gui
ROS path [6]=/home/subhojeet/Scratch/catkin_ws_teleop/src/telecarla/telecarla_rpc
ROS path [7]=/opt/ros/melodic/share
The traceback for the exception was written to the log file

Now I have installed the carla-ros-bridge following instructions at https://github.com/carla-simulator/ros-bridge but I suspect this may be a ROS_PACKAGE_PATH issue. I can't seem to update that path either from `/.bashrc.

Has the TELECARLA team faced this issue previously? If so, any help is really appreciated.

**Comment by hofbi** [comment]
It seems that you don't source the carla ros bridge path. Did you run `source /opt/carla-ros-bridge/melodic/setup.bash` or added this to your bashrc?

**Comment by j4l-Shvn** [comment]
Hi, thanks for the quick response. Here is my .bashrc --- 

source /opt/ros/melodic/setup.bash
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:/opt/carla-ros-bridge
source /opt/carla-ros-bridge/melodic/setup.bash
source ~/catkin_ws_teleop/devel/setup.bash

That is where I am a bit confused.

**Comment by hofbi** [comment]
Basically this should work fine. The only thing I don't do is the export ROS_PACKACK_PATH. You could try to remove this, but the rest should be fine. 

As a second option, could you try to manually run the source ros-bridge command in the terminal before running. Just to be sure.

**Comment by hofbi** [comment]
Did this work out? I am closing this issue as it sound more related to the carla ros bridge.
